{% set name = "corner" %}
{% set version = "2.2.0" %}
{% set sha256 = "a3b0e0f32cc9bcf9a698532cf59e9ab5b25edf42c67146545af437d16d5bac08" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - arviz >=0.9

test:
  imports:
    - corner
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/dfm/corner.py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Make some beautiful corner plots of samples.

  description: |
    corner uses matplotlib to visualize multidimensional samples using a scatterplot matrix.
    In these visualizations, each one- and two-dimensional projection of the sample is
    plotted to reveal covariances. corner was originally conceived to display the results
    of Markov Chain Monte Carlo simulations and the defaults are chosen with this application
    in mind but it can be used for displaying many qualitatively different samples.
  doc_url: http://corner.readthedocs.io/
  dev_url: https://github.com/dfm/corner.py

extra:
  recipe-maintainers:
    - guillochon
    - pkgw
    - dfm
